# Generated by Django 4.2.2 on 2023-06-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_achievement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
