# Generated by Django 4.2.2 on 2023-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventsID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventsName',
            field=models.TextField(max_length=100),
        ),
    ]
