# Generated by Django 4.2.2 on 2023-07-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_events_eventsid_alter_events_eventsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular'), ('member', 'Member')], default='regular', max_length=10),
        ),
    ]
